### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Renaud2002**
Changing the content of the readme

### CODE REVIEW

**Review by ChenMeng-SPS22 — APPROVED** [review]
Great job Fred! I do suggest to keep what's already in the README file so you can easily refer to it if needed, but it's up to you.

**Comment by Renaud2002** [comment]
Thank you, this branch was made by GitHub when I made the initial change the one, that I created base on the walk through was FredWork2 one but I can also use this one.

**Comment by ChenMeng-SPS22** [comment]
In the end this doesn't affect anything, you can merge just merge this

**Comment by Renaud2002** [comment]
It is now merge, thank you

**Pull request merged**
