### PR TITLE
Fred work2

### PR DESCRIPTION
**Pull request by Renaud2002**
changes in readme content

### CODE REVIEW

**Review by ChenMeng-SPS22 — COMMENTED** [review]
I think this is a duplicated commit? If so you can discard it

**Comment by Renaud2002** [comment]
This is the one I created using the shell terminal I wasn’t so sure.

**Comment by Renaud2002** [comment]
Hi Cheng, I have created more commits this is the branch that I will be working out of to merge to main.

**Review by ChenMeng-SPS22 — APPROVED** [review]

**Comment by ChenMeng-SPS22** [comment]
Remember to resolve merge conflict(a good opportunity to mess around and learn :) )

**Comment by Renaud2002** [comment]
Conflict resolve thank you.

**Pull request merged**
